//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalUser
    {
        public string LoginID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string QEmailAddress { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlySchedule
    {
        public int ScheduleID { get; set; }
        public int NagID { get; set; }
        public int Ordinal { get; set; }
        public byte DaysOfWeek { get; set; }
        public Entities.Enums.MonthFrequency MonthFrequency { get; set; }
        public int XMonths { get; set; }
    
        public virtual Nag Nag { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nag()
        {
            this.Recipients = new HashSet<Recipient>();
            this.MonthlySchedules = new HashSet<MonthlySchedule>();
        }
    
        public int NagID { get; set; }
        public string Subject { get; set; }
        public string ControllerID { get; set; }
        public string BodyText { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Entities.Enums.DaysOfWeek DaysOfWeek { get; set; }
        public string TimesOfDay { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> LastRun { get; set; }
        public Nullable<System.DateTime> NextRun { get; set; }
        public bool IsPaused { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> Interval { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipient> Recipients { get; set; }
        public virtual User Controller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthlySchedule> MonthlySchedules { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipient
    {
        public int NagID { get; set; }
        public string RecipientID { get; set; }
        public bool IsPaused { get; set; }
        public Nullable<System.DateTime> SnoozeUntil { get; set; }
    
        public virtual Nag Nag { get; set; }
        public virtual User User { get; set; }
    }
}
namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Recipients = new HashSet<Recipient>();
            this.ControlledNags = new HashSet<Nag>();
        }
    
        public string LoginID { get; set; }
        public string NetworkLogin { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string QEmailAddress { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipient> Recipients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nag> ControlledNags { get; set; }
    }
}
namespace Entities
{
    using System;
    
    public partial class UserInfo
    {
        public string FullName { get; set; }
        public string Initials { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string RoleName { get; set; }
    }
}
