//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QProcess.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlySchedule
    {
        public int ScheduleID { get; set; }
        public int NagID { get; set; }
        public int Ordinal { get; set; }
        public byte DaysOfWeek { get; set; }
        public Entities.Enums.MonthFrequency MonthFrequency { get; set; }
        public int XMonths { get; set; }
    
        public virtual Nag Nag { get; set; }
    }
}
