//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QProcess.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipient
    {
        public int NagID { get; set; }
        public string RecipientID { get; set; }
        public bool IsPaused { get; set; }
        public Nullable<System.DateTime> SnoozeUntil { get; set; }
    
        public virtual Nag Nag { get; set; }
        public virtual User User { get; set; }
    }
}
