CREATE TABLE QCheck_APIKeyStore(
ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
Api_Key NVARCHAR(100) NOT NULL,
Issued DATETIME NOT NULL,
NotBefore DATETIME NOT NULL,
Expires DATETIME NOT NULL,
Requestor NVARCHAR(200) NOT NULL,
OnBehalfOf NVARCHAR(200) NOT NULL,
Intent NVARCHAR(100) NOT NULL,
Approver NVARCHAR(200) NOT NULL,
IsRevoked BIT NOT NULL,
)

CREATE TABLE QCheck_JwtStore(
BearerToken NVARCHAR(100) NOT NULL,
Issued DATETIME NOT NULL,
Expires DATETIME NOT NULL,
RefreshToken NVARCHAR(100) NOT NULL,
RefreshExpires NVARCHAR(100) NOT NULL,
)

CREATE TABLE QCheck_ThirdPartyAuthAudit(
KeyValue NVARCHAR(100) NOT NULL,
KeyType NVARCHAR(10) NOT NULL,
Source NVARCHAR(100) NOT NULL,
MethodName NVARCHAR(100) NOT NULL,
Success BIT NOT NULL,
AttemptDate DATETIME NOT NULL
)