//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace QProcess.Controls.Shared
{


    public partial class DetailedUserGrid
    {

        /// <summary>
        /// GraphTest control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QProcess.Controls.Shared.QGraphs GraphTest;

        /// <summary>
        /// DataGridTest control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QProcess.Controls.Shared.QDataGrid DataGridTest;

        /// <summary>
        /// GraphTest2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QProcess.Controls.Shared.QGraphs GraphTest2;

        /// <summary>
        /// DataGridTest2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QProcess.Controls.Shared.QDataGrid DataGridTest2;
    }
}
